"""Shared constants + small deterministic helpers for find-wasted-code.

Every value here is pure/deterministic — no clock, no randomness, no host paths.
The only time input to the whole tool is the injected --date string (constants
carries none). Keeping these together makes the rule modules import-light.
"""
from __future__ import annotations

import hashlib
import re

SCHEMA_VERSION = 1
REPORT_RELPATH = "docs/wasted-code/report.md"
SENTINEL = "<!-- generated by find-wasted-code — do not edit; regenerate with /find-wasted-code -->"

# Verdict + tier vocabulary (sibling parity: confirmed/inconclusive; dismissed = suppressed).
CONFIRMED = "confirmed"
INCONCLUSIVE = "inconclusive"
TIER_BROKEN = "broken"        # deterministic — target provably absent
TIER_CANDIDATE = "candidate"  # heuristic — needs human judgment
TIER_COVERAGE = "coverage"    # baseline/unresolved — never a defect claim

SEV_BLOCKER = "blocker"
SEV_MAJOR = "major"
SEV_MINOR = "minor"

# Rule ids.
W1, W2, W3, W4, W5 = "W1", "W2", "W3", "W4", "W5"

RULE_TITLES = {
    W1: "Dead-end tool/script references",
    W2: "Broken internal links",
    W3: "Missing helpers / references",
    W4: "Footgun config (hook wired to a missing handler)",
    W5: "Silent push-through (swallowed-error baseline)",
}

# --- scan-scope policy ------------------------------------------------------
# Directories/files never READ for references (self-output, mirrors, historical
# records, fixtures). They stay in the EXISTENCE universe so links TO them are
# not false "broken" — only their CONTENT is not scanned for new references.
SCAN_EXCLUDE_PREFIXES = (
    "docs/wasted-code/",                    # our own output
    ".claude/skills/",                      # mirror of flow-skills/ (scan canonical only)
    ".agents/skills/",                      # mirror of flow-skills/
    "hooks/local/fusebase-flow-overlays/commands/",  # recovery copy of .claude/commands/
    "hooks/tests/fixtures/",               # designed-token / test fixtures
    "hooks/local/find_wasted_code/_fixtures/",       # our own golden fixtures
    "docs/release-notes/",                 # historical
    "docs/specs/",                         # design records — discuss hypothetical paths/commands
    "docs/backlog/",                       # planned-not-built notes — reference not-yet-created paths
    "docs/tmp/",                           # transient handoffs/scratch
    ".git/", "node_modules/", "state/", ".fusebase-flow-source/",
)
# Historical/record files excluded from W1/W2 instructional scanning (they cite
# retired paths on purpose; flagging them is noise, not friction).
SCAN_EXCLUDE_BASENAMES = ("CHANGELOG.md",)
SCAN_EXCLUDE_SUBSTR = ("/archive/", "/problem-catalog/")
# The canonical clean-room note file for the skill carries intentional example
# text; the false-positive reference file is excluded structurally by path.
SCAN_EXCLUDE_EXACT = ("flow-skills/find-wasted-code/references/false-positive-examples.md",)

# Backup snapshots — never in scan or existence sets.
_BACKUP_RE = re.compile(r"\.pre-(upgrade|bootstrap|refresh)-\d{8}T\d{6}Z(/|$)")

# Binary/opaque extensions we never read as text.
_BINARY_EXT = {
    ".png", ".jpg", ".jpeg", ".gif", ".webp", ".ico", ".pdf", ".zip", ".gz",
    ".tar", ".woff", ".woff2", ".ttf", ".eot", ".mp4", ".mov", ".pyc", ".so",
    ".dll", ".class", ".jar", ".bin", ".o", ".a", ".lock",
}
MAX_FILE_BYTES = 2 * 1024 * 1024  # skip + coverage-note anything larger

# Instructional surfaces W1/W2 read (markdown that carries copy-ready guidance).
def is_backup_path(rel: str) -> bool:
    return bool(_BACKUP_RE.search(rel))


def is_binary_ext(rel: str) -> bool:
    dot = rel.rfind(".")
    return dot != -1 and rel[dot:].lower() in _BINARY_EXT


def in_scan_scope(rel: str) -> bool:
    """True if this repo-relative path should be READ for references."""
    if is_backup_path(rel) or is_binary_ext(rel):
        return False
    if rel in SCAN_EXCLUDE_EXACT:
        return False
    if any(rel.startswith(p) for p in SCAN_EXCLUDE_PREFIXES):
        return False
    base = rel.rsplit("/", 1)[-1]
    if base in SCAN_EXCLUDE_BASENAMES:
        return False
    if any(s in ("/" + rel) for s in SCAN_EXCLUDE_SUBSTR):
        return False
    return True


# Root-prefix variables that make an otherwise-relative path root-explicit once
# stripped. Order matters (longest first) so we strip the full token.
ROOT_PREFIX_TOKENS = (
    "$CLAUDE_PROJECT_DIR/",
    "${CLAUDE_PROJECT_DIR}/",
    "$(git rev-parse --show-toplevel)/",
    "$ROOT/",
    "${ROOT}/",
    "./",
)

# Directory anchors that mark a path as root-explicit (resolvable from repo root).
ROOT_EXPLICIT_DIRS = (
    "hooks/", ".claude/", ".agents/", ".codex/", "flow-skills/", "agents/",
    "workflows/", "policies/", "templates/", "docs/", "audit/", ".github/",
)

# Placeholder markers → a path we must NOT try to resolve (unresolved coverage).
_PLACEHOLDER_RE = re.compile(r"[<{\[\]}>*?]|\.\.\.|\$[A-Za-z_]")


def has_placeholder(path: str) -> bool:
    return bool(_PLACEHOLDER_RE.search(path))


def strip_root_prefix(path: str):
    """Return (stripped_path, was_root_prefixed). Removes a known root-prefix var."""
    for tok in ROOT_PREFIX_TOKENS:
        if path.startswith(tok):
            return path[len(tok):], True
    return path, False


def is_root_explicit(path: str) -> bool:
    """A path resolvable from the repo root (not cwd-ambiguous)."""
    return any(path.startswith(d) for d in ROOT_EXPLICIT_DIRS)


def finding_id(rule: str, path: str, line: int, evidence: str) -> str:
    h = hashlib.sha256(f"{rule}|{path}|{line}|{evidence}".encode("utf-8")).hexdigest()
    return h[:12]


# --- redaction + report-structure safety ------------------------------------
# Token-shaped substrings are replaced before rendering so the tracked report
# never trips the staged secret scanner (docs/wasted-code/ is NOT scan-excluded).
# This mirrors every "anywhere-matching" high/medium pattern in
# policies/secret-patterns.yml; the --selftest runs the repo's OWN scanner over a
# probe-seeded report and fails if any pattern would still fire, so this set can
# never silently drift below the scanner it must satisfy.
_TOKEN_RES = [
    re.compile(r"AKIA[0-9A-Z]{12,}"),                                   # aws access key
    re.compile(r"(?i)aws.{0,20}(?:secret|access).{0,20}['\":\s]+[0-9a-zA-Z/+]{40}"),
    re.compile(r"-----BEGIN (?:RSA |EC |DSA |OPENSSH )?PRIVATE KEY-----"),
    re.compile(r"gh[psoure]_[A-Za-z0-9_]{20,}"),                        # github tokens
    re.compile(r"github_pat_[A-Za-z0-9_]{20,}"),
    re.compile(r"glpat-[A-Za-z0-9_-]{16,}"),                            # gitlab pat
    re.compile(r"\b(?:sk|rk|pk)_(?:live|test)_[0-9a-zA-Z]{20,}"),        # stripe
    re.compile(r"sk-ant-[A-Za-z0-9_-]{16,}"),                           # anthropic
    re.compile(r"sk-[A-Za-z0-9_-]{32,}"),                               # openai
    re.compile(r"xox[a-z]-[A-Za-z0-9-]{4,}"),                          # slack token (incl. short structured)
    re.compile(r"https://hooks\.slack\.com/services/[A-Za-z0-9/]+"),    # slack webhook
    re.compile(r"(?i)(?:set-cookie|cookie)\s*[:=]\s*[\w.=-]+=[A-Za-z0-9+/=._-]{16,}"),  # cookie
    re.compile(r"SG\.[A-Za-z0-9_-]{20,}\.[A-Za-z0-9_-]{20,}"),          # sendgrid
    re.compile(r"eyJ[A-Za-z0-9_-]{16,}\.[A-Za-z0-9_-]{16,}\.[A-Za-z0-9_-]{6,}"),  # jwt
    re.compile(r"ya29\.[A-Za-z0-9_-]{16,}"),                            # google oauth
    re.compile(r"(?i)twilio.{0,20}(?:auth|token).{0,20}['\":\s]+[a-f0-9]{32}"),
    re.compile(r"://[^/\s:@]+:[^/\s:@]{4,}@"),                          # creds in url
    re.compile(r"(?i)(?:password|passwd|secret|token|api[_-]?key)\s*[:=]\s*\S{8,}"),
    re.compile(r"\b[0-9a-f]{40,}\b"),                                    # long hex
]
REDACTED = "‹redacted›"


def redact(text: str) -> str:
    for rx in _TOKEN_RES:
        text = rx.sub(REDACTED, text)
    return text


def code_escape(text: str) -> str:
    """Render an arbitrary snippet safe as inline code in a Markdown table cell.

    Redact tokens first, then neutralise the characters that could break table
    structure or re-introduce live Markdown the report's own W2 would parse.
    """
    text = redact(text)
    text = text.replace("\r", " ").replace("\n", " ").replace("\t", " ")
    text = text.replace("`", "ˋ").replace("|", "│")
    return text.strip()


_DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")


def valid_date(s: str) -> bool:
    """Accept only YYYY-MM-DD so the --date value can never inject report text."""
    return bool(_DATE_RE.match(s))


_HEREDOC_RE = re.compile(r"<<[-~]?\s*['\"]?(\w+)['\"]?")


def strip_heredocs(lines):
    """Blank out heredoc bodies so their contents are not read as shell statements
    (W3 source detection) or counted as swallows (W5 baseline)."""
    out = []
    tag = None
    for line in lines:
        if tag is not None:
            out.append("")
            if line.strip() == tag:
                tag = None
            continue
        m = _HEREDOC_RE.search(line)
        out.append(line)
        if m:
            tag = m.group(1)
    return out
