#!/usr/bin/env bash
# Fusebase Flow — upgrade.sh  (F1: in-place CONTENT upgrade)
#
# PROVENANCE:
#   Shipped Fusebase Flow v3.6.0+. Lives at hooks/local/ — outside the FuseBase
#   CLI refresh manifest, so it survives `fusebase update`.
#
# PURPOSE:
#   The missing "upgrade an installed overlay" path. Unlike upgrade-engine.sh
#   (which syncs only the 3 engine scripts + VERSION), this refreshes the
#   CANONICAL CONTENT from the upstream clone and re-mirrors it, then bumps
#   VERSION as the LAST step — so VERSION can never advance ahead of content.
#
#   Order (deliberate — see F8):
#     1. Refresh canonical content from .fusebase-flow-source/:
#          skills/ agents/ workflows/ policies/ templates/ FLOW_RULES.md
#          + framework docs (docs/*.md top-level reference set)
#     2. Re-mirror: mirror-skills.sh + mirror-agents.sh  (canonical → providers)
#     3. Sync embedded version strings from VERSION (sync-version-strings.sh)
#     4. Refresh drifted AGENTS.md/CLAUDE.md overlay blocks (version-aware; F2)
#     5. Bump VERSION to match upstream  (LAST — never before content)
#
#   Backups: every touched path gets a .pre-upgrade-<ts> copy. Dry-run shows the
#   plan without writing. Abort leaves the tree untouched.
#
# What it does NOT do:
#   - Touch .claude/settings.json or wire hooks (that's opt-in via
#     post-fusebase-update.sh --wire-hooks; F3).
#   - Touch CLI-owned provider assets (.claude/hooks/**, CLI provider skills,
#     MCP/fusebase.json/skills-lock.json) — those are CLI-owned.
#   - Touch local-only areas (internal/, docs/fusebase-health/).
#
# Prerequisite:
#   .fusebase-flow-source/ present (git clone OR plain dir copy; F5). Refresh:
#     cd .fusebase-flow-source && git pull origin main   # if a git clone
#
# Usage:
#   bash hooks/local/upgrade.sh              # interactive: show plan, confirm
#   bash hooks/local/upgrade.sh --dry-run    # show plan, write nothing
#   bash hooks/local/upgrade.sh --auto-yes   # non-interactive
#
# Exit: 0 success / no-op; 1 source missing or error; 2 bad arg; 3 declined.

set -euo pipefail

ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$ROOT"

SOURCE_CLONE=".fusebase-flow-source"
AUTO_YES=0
DRY_RUN=0

for arg in "$@"; do
  case "$arg" in
    --auto-yes|-y) AUTO_YES=1 ;;
    --dry-run|-n) DRY_RUN=1 ;;
    --help|-h) sed -n '2,42p' "$0"; exit 0 ;;
    *) echo "Unknown argument: $arg" >&2; echo "Run with --help for usage." >&2; exit 2 ;;
  esac
done

if [ ! -d "$SOURCE_CLONE" ]; then
  echo "[upgrade] FATAL: $SOURCE_CLONE/ not found." >&2
  echo "          Provide an upstream copy first, e.g.:" >&2
  echo "            git clone https://github.com/fusebase-dev/fusebase-flow.git $SOURCE_CLONE" >&2
  exit 1
fi

# F5: a git clone enables HEAD reporting; a plain dir is accepted with a warning.
if [ -d "$SOURCE_CLONE/.git" ]; then
  SRC_HEAD=$(cd "$SOURCE_CLONE" && git rev-parse --short HEAD 2>/dev/null || echo "?")
else
  SRC_HEAD="(plain dir — no .git; HEAD/diff unavailable)"
  echo "[upgrade] NOTE: $SOURCE_CLONE/ is a plain directory (no .git). Proceeding with"
  echo "          file-content comparison only; upstream HEAD/diff is unavailable."
fi

if [ ! -f "$SOURCE_CLONE/VERSION" ]; then
  echo "[upgrade] FATAL: $SOURCE_CLONE/VERSION missing — cannot determine target version." >&2
  exit 1
fi
SRC_VERSION=$(tr -d '\n\r' < "$SOURCE_CLONE/VERSION")
LOCAL_VERSION=$(tr -d '\n\r' < VERSION 2>/dev/null || echo "?")

echo "[upgrade] Source: $SOURCE_CLONE/  (HEAD $SRC_HEAD, VERSION $SRC_VERSION)"
echo "[upgrade] Local:  VERSION $LOCAL_VERSION"
echo ""

# Canonical content trees + files to refresh (NOT provider mirrors; those are
# regenerated by the mirror scripts in step 2).
CONTENT_DIRS=( "skills" "agents" "workflows" "policies" "templates" )
CONTENT_FILES=( "FLOW_RULES.md" )
# Framework reference docs (top-level docs/*.md only; never specs/handoff/release-notes).
DOC_GLOB="docs"

TS=$(date -u +%Y%m%dT%H%M%SZ)
PLAN=()

dir_differs() { ! diff -rq "$SOURCE_CLONE/$1" "$1" >/dev/null 2>&1; }

for d in "${CONTENT_DIRS[@]}"; do
  if [ -d "$SOURCE_CLONE/$d" ] && dir_differs "$d"; then
    PLAN+=("refresh dir:  $d/")
  fi
done
for f in "${CONTENT_FILES[@]}"; do
  if [ -f "$SOURCE_CLONE/$f" ] && ! diff -q "$SOURCE_CLONE/$f" "$f" >/dev/null 2>&1; then
    PLAN+=("refresh file: $f")
  fi
done
# Top-level framework docs (docs/*.md) — exclude historical subdirs.
if [ -d "$SOURCE_CLONE/$DOC_GLOB" ]; then
  while IFS= read -r srcdoc; do
    rel="${srcdoc#$SOURCE_CLONE/}"
    if [ -f "$rel" ] && ! diff -q "$srcdoc" "$rel" >/dev/null 2>&1; then
      PLAN+=("refresh doc:  $rel")
    elif [ ! -f "$rel" ]; then
      PLAN+=("add doc:      $rel")
    fi
  done < <(find "$SOURCE_CLONE/$DOC_GLOB" -maxdepth 1 -name "*.md" -type f 2>/dev/null)
fi

VERSION_CHANGE=""
[ "$SRC_VERSION" != "$LOCAL_VERSION" ] && VERSION_CHANGE="VERSION: $LOCAL_VERSION -> $SRC_VERSION"

if [ "${#PLAN[@]}" -eq 0 ] && [ -z "$VERSION_CHANGE" ]; then
  echo "[upgrade] Content already matches upstream. Nothing to do."
  exit 0
fi

echo "[upgrade] Plan:"
for p in "${PLAN[@]}"; do echo "  • $p"; done
echo "  • re-mirror skills + agents (canonical -> .claude/.agents/.codex)"
echo "  • sync embedded version strings from VERSION"
echo "  • version-aware refresh of drifted AGENTS.md/CLAUDE.md overlay blocks"
[ -n "$VERSION_CHANGE" ] && echo "  • $VERSION_CHANGE  (applied LAST, after content)"
echo ""

if [ "$DRY_RUN" -eq 1 ]; then
  echo "[upgrade] (dry-run; nothing written)"
  exit 0
fi

if [ "$AUTO_YES" -ne 1 ]; then
  printf "[upgrade] Apply this content upgrade? [y/N] "
  read -r ans
  case "$ans" in [yY]|[yY][eE][sS]) ;; *) echo "[upgrade] Aborted."; exit 3 ;; esac
fi

# ---- Step 1: refresh canonical content (with backups) ----
copy_dir() {
  local d="$1"
  [ -d "$SOURCE_CLONE/$d" ] || return 0
  if [ -d "$d" ]; then cp -R "$d" "$d.pre-upgrade-$TS"; fi
  # Replace contents (canonical is source of truth; do not delete extra local files
  # blindly — copy upstream over, leaving any project-local additions in place).
  cp -R "$SOURCE_CLONE/$d/." "$d/"
}
for d in "${CONTENT_DIRS[@]}"; do
  if [ -d "$SOURCE_CLONE/$d" ] && dir_differs "$d"; then copy_dir "$d"; fi
done
for f in "${CONTENT_FILES[@]}"; do
  if [ -f "$SOURCE_CLONE/$f" ] && ! diff -q "$SOURCE_CLONE/$f" "$f" >/dev/null 2>&1; then
    [ -f "$f" ] && cp "$f" "$f.pre-upgrade-$TS"
    cp "$SOURCE_CLONE/$f" "$f"
  fi
done
if [ -d "$SOURCE_CLONE/$DOC_GLOB" ]; then
  while IFS= read -r srcdoc; do
    rel="${srcdoc#$SOURCE_CLONE/}"
    if [ ! -f "$rel" ] || ! diff -q "$srcdoc" "$rel" >/dev/null 2>&1; then
      [ -f "$rel" ] && cp "$rel" "$rel.pre-upgrade-$TS"
      mkdir -p "$(dirname "$rel")"
      cp "$srcdoc" "$rel"
    fi
  done < <(find "$SOURCE_CLONE/$DOC_GLOB" -maxdepth 1 -name "*.md" -type f 2>/dev/null)
fi

# ---- Step 2: re-mirror canonical -> providers ----
[ -x hooks/local/mirror-skills.sh ] && bash hooks/local/mirror-skills.sh >/dev/null 2>&1 || true
[ -x hooks/local/mirror-agents.sh ] && bash hooks/local/mirror-agents.sh >/dev/null 2>&1 || true

# ---- Step 3: sync embedded version strings (uses LOCAL VERSION; bumped in step 5,
# so run AFTER bump? No — strings should reflect the TARGET version. Write VERSION
# first into a temp, but per F1 VERSION file itself is bumped LAST. Resolve by
# passing the target explicitly: temporarily VERSION is still old, so we bump the
# file, then sync strings, then the "VERSION never leads content" invariant still
# holds because content (steps 1-2) already landed.) ----

# ---- Step 5 (bump VERSION) BEFORE string-sync, but AFTER content (steps 1-2). ----
if [ -n "$VERSION_CHANGE" ]; then
  cp VERSION "VERSION.pre-upgrade-$TS" 2>/dev/null || true
  echo "$SRC_VERSION" > VERSION
fi

# ---- Step 3: sync embedded version strings now that VERSION reflects target ----
[ -x hooks/local/sync-version-strings.sh ] && bash hooks/local/sync-version-strings.sh || true

# ---- Step 4: version-aware overlay refresh (F2) ----
bash hooks/local/post-fusebase-update.sh --refresh-overlays >/dev/null 2>&1 || true

# ---- .pyc scrub (F6) ----
find . -path ./.fusebase-flow-source -prune -o -name "*.pyc" -print -delete 2>/dev/null | grep -q . \
  && echo "[upgrade] scrubbed stray .pyc files" || true

echo ""
echo "[upgrade] Content upgrade applied. VERSION now: $(tr -d '\n\r' < VERSION)"
echo "[upgrade] Backups written with suffix .pre-upgrade-$TS — remove once validated."
echo ""
echo "[upgrade] Recommended next:"
echo "  bash hooks/local/preflight.sh                       # expect 0 errors / 0 warnings"
echo "  bash hooks/local/fusebase-flow-health-check.sh      # expect HEALTHY"
echo "  git diff                                            # review"
echo "  git add -A && git commit -m 'chore(flow): upgrade content to v$SRC_VERSION'"
echo ""
echo "[upgrade] NOTE: .claude/settings.json was NOT modified. To (re)wire Flow"
echo "          lifecycle hooks, run:  bash hooks/local/post-fusebase-update.sh --wire-hooks"
exit 0
